# =================================
# DEVELOPMENT ENVIRONMENT CONFIGURATION
# =================================

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/employee
spring.datasource.username=postgres
spring.datasource.password=cuong1182004

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
# Cloudinary Configuration (Điền key thật của bạn vào đây, không cần ngoặc kép)
cloudinary.cloud_name=dj9r2qksh
cloudinary.api_key=647997488949428
cloudinary.api_secret=vaBtNxURR9FKE8Bz58PVW-upUSQ

# Development specific settings
logging.level.com.example=DEBUG
management.endpoints.web.exposure.include=*
